# Full language list (matches gTTS-supported languages so text-to-speech
# works for every entry). Codes verified against gtts.lang.tts_langs().
LANGUAGES = {
    "auto": "Detect Language",
    "af": "Afrikaans",
    "ar": "Arabic",
    "bg": "Bulgarian",
    "bn": "Bengali",
    "bs": "Bosnian",
    "ca": "Catalan",
    "cs": "Czech",
    "da": "Danish",
    "de": "German",
    "el": "Greek",
    "en": "English",
    "es": "Spanish",
    "et": "Estonian",
    "fi": "Finnish",
    "fr": "French",
    "gu": "Gujarati",
    "hi": "Hindi",
    "hr": "Croatian",
    "hu": "Hungarian",
    "id": "Indonesian",
    "is": "Icelandic",
    "it": "Italian",
    "ja": "Japanese",
    "jw": "Javanese",
    "km": "Khmer",
    "kn": "Kannada",
    "ko": "Korean",
    "la": "Latin",
    "lv": "Latvian",
    "ml": "Malayalam",
    "mr": "Marathi",
    "my": "Myanmar (Burmese)",
    "ne": "Nepali",
    "nl": "Dutch",
    "no": "Norwegian",
    "pa": "Punjabi",
    "pl": "Polish",
    "pt": "Portuguese",
    "ro": "Romanian",
    "ru": "Russian",
    "si": "Sinhala",
    "sk": "Slovak",
    "sq": "Albanian",
    "sr": "Serbian",
    "su": "Sundanese",
    "sv": "Swedish",
    "sw": "Swahili",
    "ta": "Tamil",
    "te": "Telugu",
    "th": "Thai",
    "tl": "Filipino",
    "tr": "Turkish",
    "uk": "Ukrainian",
    "ur": "Urdu",
    "vi": "Vietnamese",
    "zh-CN": "Chinese (Simplified)",
}

# Languages gTTS can actually speak (verified via gtts.lang.tts_langs()).
# "pa" (Punjabi) is kept in LANGUAGES for translation but has no gTTS voice.
TTS_SUPPORTED = set(LANGUAGES.keys()) - {"auto", "pa"}
TTS_CODE_FIX = {"zh-CN": "zh-CN"}  # gTTS accepts zh-CN directly

# langdetect codes -> our LANGUAGES codes (where they differ)
DETECT_CODE_MAP = {
    "zh-cn": "zh-CN",
    "zh-tw": "zh-CN",
}
